AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 35
  
Metrics/BlockLength:
  Max: 40 
  
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

